input:
  label: yr_locationforecast
  http_client:
    url: https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=51.5&lon=0
    verb: GET
    headers:
      User-Agent: "yr-benthos-test/0.1.0"
    rate_limit: chill_down
    timeout: 5s
    retry_period: 1s
    max_retry_backoff: 300s
    retries: 3
    proxy_url: ""
    payload: ""
    drop_empty_bodies: true
    oauth2:
      enabled: false
      client_key: ""
      client_secret: ""
      token_url: ""
    jwt:
      enabled: false
      private_key_file: ""
      signing_method: ""
    stream:
      enabled: false
      reconnect: true
      codec: lines
      max_buffer: 1e+06
pipeline:
  processors:
    - mapping: from "./yr.blobl"
output:
  broker:
    outputs:
      - label: bq_ingest
        gcp_bigquery:
          project: rm-data-platform-dev
          dataset: dbt_rasmus_nes
          table: benthos_yr_ingest
          format: NEWLINE_DELIMITED_JSON
          max_in_flight: 64
          write_disposition: WRITE_APPEND
          create_disposition: CREATE_IF_NEEDED
          ignore_unknown_values: false
          max_bad_records: 0
          auto_detect: false
          csv:
            field_delimiter: ','
            allow_jagged_rows: false
            allow_quoted_newlines: false
            encoding: UTF-8
            skip_leading_rows: 1
          batching:
            count: 0
            byte_size: 0
            period: ""
            check: ""
      - label: yr_stdout
        stdout:
          codec: lines
rate_limit_resources:
  - label: chill_down
    local:
      count: 1
      interval: 10s # Hacky: set this to a number higher than `Max function duration` to restrict function to only 1 request.